name: Build and Deploy Docker Image to EC2

on:
  push:
    branches:
      - master  # Trigger when code is pushed to the 'master' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Check out code
        uses: actions/checkout@v2

      # Step 2: Configure AWS Credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Step 3: Log in to AWS ECR
      - name: Log in to AWS ECR
        run: |
          aws --version
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 539247459542.dkr.ecr.us-east-1.amazonaws.com

      # Step 4: Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t nginx-web-app .

      # Step 5: Tag the Docker image
      - name: Tag Docker image
        run: |
          docker tag nginx-web-app:latest 539247459542.dkr.ecr.us-east-1.amazonaws.com/nginx-web-app:latest

      # Step 6: Push the Docker image to ECR
      - name: Push Docker image to ECR
        run: |
          docker push 539247459542.dkr.ecr.us-east-1.amazonaws.com/nginx-web-app:latest

      # Step 7: SSH into EC2 and deploy Docker container
      - name: SSH into EC2 and deploy Docker container
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            sudo docker pull 539247459542.dkr.ecr.us-east-1.amazonaws.com/nginx-web-app:latest
            sudo docker stop $(sudo docker ps -q --filter ancestor=539247459542.dkr.ecr.us-east-1.amazonaws.com/nginx-web-app:latest)
            sudo docker rm $(sudo docker ps -a -q --filter ancestor=539247459542.dkr.ecr.us-east-1.amazonaws.com/nginx-web-app:latest)
            sudo docker run -d -p 8080:80 539247459542.dkr.ecr.us-east-1.amazonaws.com/nginx-web-app:latest
